import { Inter } from 'next/font/google'
import Image from 'next/image';
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'SG Lens Guide',
  description: 'Generated by Richard Brookman',
}

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="root__header header--thin bg-gradient-to-r from-purple-800 to-blue-500">
          <span className="text-white font-light">Best sunglasses in the game.</span>
        </nav>
        <nav className="root__header">
          <ul className="w-3/5 flex flex-row justify-evenly items-center">
            <li>
            <a href="/">
            <Image src="/images/sg_logo.png" alt="Photo 1" width={180} height={140} />
            </a>
            </li>
            <li className="header__link"><a href="/shop">Sunglasses</a></li>
            <li className="header__link">Prescriptions</li>
            <li className="header__link">Goggles</li>
            <li className="header__link">Limited Edition</li>
            <li className="header__link">More</li>
          </ul>
          <div className="w-2/5 flex flex-row justify-end items-center">
            <span className="header__link mr-10">Lang</span>
            <span className="header__link mr-12">Basket</span>
          </div>
        </nav>
        {children}
        </body>
    </html>
  )
}
